biolib_version: 2


modules:
    main:
        image: 'local-docker://deeplocpro:latest'
        command: deeplocpro
        input_files:
            - COPY / /
        output_files: 

            - COPY /output/deeptmhmm/TMRs.gff3 /
            - COPY /output/deeptmhmm/plot.png /
            - COPY /output/deeptmhmm/deeptmhmm_results.md /
            - COPY /output/*/*.pdb /
            - COPY /output/output.html /


        source_files: []


arguments:

    -
        default_value: src/sample.fasta
        description: 'File submission: Input the sequences or upload a local fasta file'
        key: '--fasta'
        key_value_separator: ' '
        required: true
        type: text-file



# this goes in config.yml
citation:
    entry_type: misc
    author: >-
        Santiago Gutierrez, Wojciech G. Tyczynski, Wouter Boomsma, Felix Teufel, Ole Winther
    howpublished: Web Server
    month: '12'
    title: 'MembraneFold: Visualising transmembrane protein structure and topology'
    year: '2022'
    url: https://www.biorxiv.org/content/10.1101/2022.12.06.518085v1
    doi: https://doi.org/10.1101/2022.12.06.518085 



main_output_file: /output.html
